_target_: lumos.datasets.ag_disk_dataset.AGDiskDataset
key: "vis"
save_format: "npz"
batch_size: ${datamodule.batch_size}
min_window_size: ${datamodule.min_window_size}
max_window_size: ${datamodule.seq_len}
proprio_state: ${datamodule.proprioception_dims}
obs_space: ${datamodule.observation_space}
pad: true
for_wm: false
lang_folder: "lang_paraphrase-MiniLM-L3-v2"
num_workers: 2
