_target_: lumos.datasets.wm_disk_state_multistep_dataset.WMDiskStateDataset
key: "state"
save_format: "npz"
use_cached_data: false
reset_prob: ${datamodule.reset_prob}
batch_size: ${datamodule.batch_size}
min_window_size: ${datamodule.seq_len}
max_window_size: ${datamodule.seq_len}
proprio_state: ${datamodule.proprioception_dims}
obs_space: ${datamodule.observation_space}
pad: false
for_wm: true
lang_folder: ""
num_workers: 24
action_steps: 4
