_target_: lumos.behavior_models.actor_critic.critic.Critic
perceptual_features: ???
latent_goal_features: ${behavior_model.visual_goal.latent_goal_features}
plan_features: ???
hidden_dim: 1024
layers: 8
layer_norm: true
activation: elu