accelerator: gpu
devices: ${devices}
num_nodes: 1
precision: 32
max_epochs: -1
max_steps: 2000000
log_every_n_steps: 500
val_check_interval: 1.0
deterministic: True
check_val_every_n_epoch: 20
num_sanity_val_steps: 0
