_target_: torch.optim.AdamW            
lr: 3e-4                              
betas: [0.9, 0.999]                  
eps: 1e-5                              
weight_decay: 0.01                        
amsgrad: False                         