_target_: lumos.datasets.base_wm_disk_dataset.BaseWMDiskDataset
key: "vis"
save_format: "npz"
use_cached_data: ${datamodule.use_cached_data}
reset_prob: ${datamodule.reset_prob}
min_window_size: ${datamodule.seq_len}
max_window_size: ${datamodule.seq_len}
proprio_state: ${datamodule.proprioception_dims}
obs_space: ${datamodule.observation_space}
action_chunk_size: ${datamodule.action_chunk_size}
pad: false
for_wm: true
lang_folder: ""
num_workers: 8
