defaults:
  - datasets: base_vision
  - transforms: wm_basic
  - proprioception_dims: robot_full
  - batch_sampler: equidistant

_target_: lumos.datasets.base_data_module.BaseDataModule
_recursive_: false
root_data_dir: ${root}/dataset/calvin/64_task_D_D
action_space: 7
action_max: [1., 1., 1., 1., 1., 1., 1.,]
action_min: [-1., -1., -1., -1., -1., -1., -1]
shuffle_val: false
load_feats: false
use_cached_data: true

reset_prob: 0.01
train_batch_size: 50
val_batch_size: 50
seq_len: 50