defaults:
  - base
  - override datasets: base_hybrid
  - override transforms: hybrid_wm_minmax
  - override proprioception_dims: robot_scene_rot6d
  - override observation_space: rgb_static_gripper_state_rel_act

root_data_dir: ${root}/dataset/calvin/task_D_D_rgb64_rot6d/
use_gripper_camera: true