defaults:
  - base
  - override datasets: base_state
  - override transforms: state_wm_minmax
  - override proprioception_dims: robot_scene_rot6d
  - override observation_space: state_rel_act

root_data_dir: ${root}/dataset/calvin/task_D_D_state_rot6d/