defaults:
  - encoder: transformer_encoder
  - decoder: transformer_decoder
  - rgb_decoder: cnn_decoder
  - rssm: default
  - amp: default
  - optimizer: adamw
  - loss: patch_wm

_target_: lumos.world_models.dreamer_v2.DreamerV2
_recursive_: false
name: dreamer_v2
train_batch_size: ${datamodule.train_batch_size}
val_batch_size: ${datamodule.val_batch_size}

