_target_: lumos.behavior_models.decoders.gaussian_decoder.GaussianDecoder
perceptual_features: ???
latent_goal_features: ${behavior_model.visual_goal.latent_goal_features}
plan_features: ???
hidden_size: 256
layers: 8
layer_norm: true
activation: elu
out_features: ${datamodule.action_space}
log_std_min: -5.0
log_std_max: 2.0
