defaults:
  - setup
  - datamodule: static_gripper_cam
  - world_model: dreamer_v2
  - _self_

exp_dir: ${wm_chk_dir}
wm_chk_dir: /home/lagandua/projects/lumos/logs/ckpts/vision.ckpt
output_file: "visionwm_features.pkl"
device: 0