defaults:
  - setup
  - datamodule: vision_wm_real
  - world_model: dreamer_v2_vision
  # - _self_

exp_dir: ${wm_chk_dir}
# Vision only - Rot6D - MinMax - Small
wm_chk_dir: "/home/lagandua/projects/lumos/logs/runs/2025-04-24/16-19-20/model_weights/695000.ckpt"
output_file: "cached_feats_vision_small_seq50_700K.pkl"
device: 0