defaults:
  - setup
  - datamodule: static_gripper_cam
  - world_model: dreamer_v2
  - override datamodule/batch_sampler: ac_equidistant
  - _self_

exp_dir: ${wm_chk_dir}
wm_chk_dir: /path/to/your/model/checkpoint/X.ckpt
output_file: "visionwm_features.pkl"
device: 0