defaults:
  - setup

input_dir: ${root}/dataset/calvin/task_D_D
output_dir: ${root}/dataset/calvin/30_64_rgbsg
desired_keys: ['actions', 'rel_actions', 'robot_obs', 'scene_obs', 'rgb_static', 'rgb_gripper']  # ['actions', 'rel_actions', 'robot_obs', 'scene_obs', 'rgb_static', 'rgb_gripper', 'rgb_tactile', 'depth_static', 'depth_gripper', 'depth_tactile']
desired_resolution: 64