defaults:
  - setup

input_dir: /home/lagandua/projects/diffusion_policy/data/task_D_D
# input_dir: /home/lagandua/projects/lumos/dataset/calvin/calvin_debug_dataset
output_dir: ${root}/dataset/calvin/play_rgb64_rot6d
desired_keys: ['rel_actions', 'robot_obs', 'scene_obs', "rgb_static", "rgb_gripper"]  # ['actions', 'rel_actions', 'robot_obs', 'scene_obs', 'rgb_static', 'rgb_gripper', 'rgb_tactile', 'depth_static', 'depth_gripper', 'depth_tactile']
desired_resolution: 64