defaults:
  - setup
  - callbacks: wm_default
  - datamodule: hybrid_wm
  - world_model: dreamer_v2_hybrid
  - trainer: wm_default
  - logger: wandb
  - calvin_env: new_default
  - _self_

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

devices: [0]
script: state_wm

hydra:
  run:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir
          - datamodule.root_data_dir
