_target_: lumos.world_models.decoders.hybrid_decoder.HybridDecoder
in_dim: ???
cnn_depth: ${world_model.encoder.cnn_depth}
kernels: [5, 5, 6, 6]
stride: 2
layer_norm: true
activation: elu
mlp_layers: 0
state_mlp_layers: [400]
state_out_dim: ${world_model.encoder_state.state_dim}