train:
  robot_obs:
    - _target_: lumos.utils.transforms.NormalizeVector
  scene_obs:
    - _target_: lumos.utils.transforms.NormalizeVector


val:
  rgb_static:
    - _target_: calvin_agent.utils.transforms.ScaleImageTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.5,]
      std: [0.5,]

  rgb_gripper:
    - _target_: calvin_agent.utils.transforms.ScaleImageTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.5,]
      std: [0.5,]

  robot_obs:
    - _target_: lumos.utils.transforms.NormalizeVector
  scene_obs:
    - _target_: lumos.utils.transforms.NormalizeVector
